apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-main-pvc
  namespace: webpos-infra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: hostpath
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pos-pvc
  namespace: webpos-infra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: hostpath