# 실제 사용 시 base64로 인코딩된 값 사용 필요
# echo -n 'password' | base64
apiVersion: v1
kind: Secret
metadata:
  name: mysql-main-secret
  namespace: webpos-infra
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk  # rootpassword
  MYSQL_PASSWORD: bWFpbnBhc3N3b3Jk      # mainpassword
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-pos-secret
  namespace: webpos-infra
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk  # rootpassword
  MYSQL_PASSWORD: cG9zcGFzc3dvcmQ=      # pospassword