version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - webpos-network

  kafka-service:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka-service
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-service:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - webpos-network

  redis-service:
    image: redis:latest
    container_name: redis-service
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - webpos-network

  mysql-pos:
    image: mysql:8.0
    container_name: mysql-pos
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pos_server
      MYSQL_USER: posuser
      MYSQL_PASSWORD: pospassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-pos-data:/var/lib/mysql
    networks:
      - webpos-network

  mysql-main:
    image: mysql:8.0
    container_name: mysql-main
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: main_server
      MYSQL_USER: mainuser
      MYSQL_PASSWORD: mainpassword
    ports:
      - "3307:3306"
    volumes:
      - mysql-main-data:/var/lib/mysql
    networks:
      - webpos-network

volumes:
  redis-data:
  mysql-pos-data:
  mysql-main-data:

networks:
  webpos-network:
    driver: bridge