version: '3.8'

# MSA Infrastructure Services
# This file contains only the infrastructure components (databases, message queues, etc.)
# Application services are defined in the main docker-compose.yml

services:
  # Main Server Database
  mysql-main:
    image: mysql:8.0
    container_name: msa-mysql-main
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: main_server
      MYSQL_USER: mainuser
      MYSQL_PASSWORD: mainpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_main_data:/var/lib/mysql
      - ./init/main-server.sql:/docker-entrypoint-initdb.d/init.sql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --sql-mode=STRICT_TRANS_TABLES,NO_ZERO_DATE,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO
    networks:
      - msa-network

  # POS Server Database (separate database for MSA)
  mysql-pos:
    image: mysql:8.0
    container_name: msa-mysql-pos
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: pos_server
      MYSQL_USER: posuser
      MYSQL_PASSWORD: pospassword
    ports:
      - "3307:3306"
    volumes:
      - mysql_pos_data:/var/lib/mysql
      - ./init/pos-server.sql:/docker-entrypoint-initdb.d/init.sql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --sql-mode=STRICT_TRANS_TABLES,NO_ZERO_DATE,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO
    networks:
      - msa-network

  # Shared Redis for caching
  redis:
    image: redis:7-alpine
    container_name: msa-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - msa-network

  # Message Queue for service communication
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: msa-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - msa-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: msa-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - msa-network

  # Service Discovery (optional - for future enhancement)
  consul:
    image: consul:latest
    container_name: msa-consul
    ports:
      - "8500:8500"
    command: agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0
    networks:
      - msa-network

volumes:
  mysql_main_data:
  mysql_pos_data:
  redis_data:

networks:
  msa-network:
    driver: bridge