server:
  port: 8080

spring:
  application:
    name: pos-server
  
  # Database configuration for Kubernetes environment
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://mysql-pos.webpos-infra:3306/pos_server}
    username: ${SPRING_DATASOURCE_USERNAME:posuser}
    password: ${SPRING_DATASOURCE_PASSWORD:pospassword}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
  
  # Redis configuration for Kubernetes
  data:
    redis:
      host: ${SPRING_REDIS_HOST:redis.webpos-infra}
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0
  
  # Kafka configuration for Kubernetes
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka.webpos-infra:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: pos-server-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

# External service configuration
external:
  main-server:
    url: ${MAIN_SERVER_URL:http://main-server.webpos:8080}
    timeout: 5000

# Actuator for health checks and monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

# Kubernetes specific logging
logging:
  level:
    com.gijun: INFO
    org.springframework.kafka: WARN
    org.hibernate.SQL: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{traceId:-},%X{spanId:-}] %logger{36} - %msg%n"